// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aiwwquousyzdkagporcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpd3dxdW91c3l6ZGthZ3BvcmN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzI1OTYsImV4cCI6MjA3MzcwODU5Nn0.60xyW8E5MSbjhtpsxC9phjlf1oGaapBwQIHmL8-bMrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});